# php:8.3.14 fpm-alpine

services:
  #PHP
  laravel_php: # nome declarado no serviço no docker-compose
    build:
      context: ./images/php # imagem que foi contruida no dockerfile
    container_name: laravel_php # criando o nome do container
    volumes:
      - ./volume_app:/var/www/html # mapeando o volume do host para o container
    networks:
      - laravel_network # rede que o container vai usar

  #NGINX
  laravel_nginx:
    image: nginx:stable-alpine3.20
    container_name: laravel_nginx
    volumes:
     - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./volume_app:/var/www/html
    ports:
      - "80:80"
    networks:
      - laravel_network
    depends_on:
      - laravel_php


  #MySQL
  laravel_mysql:
     image: mysql:8.4.3
     container_name: laravel_mysql
     ports:
       - "3306:3306"
     environment:
        MYSQL_ROOT_PASSWORD: root
     networks:
        - laravel_network
     volumes:
        - ./volume_data:/var/lib/mysql
      
        
 # Network
networks:
  laravel_network:
    driver: bridge
    name: laravel_network

